services:
  front:
    build: ./front/blog_martinique/
    volumes:
      - /var/opt/app:/usr/src/app
    ports:
      - 5173:5173


  back: 
    build: ./back_projet/
    volumes:
      - /var/opt/app:/usr/src/app
    ports:
      - 8181:8181

      