services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  front:
    build: ./front/blog_martinique/
    volumes:
      - /var/opt/app:/usr/src/app
    ports:
      - 5173:5173


  back: 
    build: ./back_projet/
    volumes:
      - /var/opt/app:/usr/src/app
    ports:
      - 8181:8181

      

